name: Super 6 Reminder Scheduler

on:
  workflow_dispatch:

  schedule:
    - cron: "0 * * * *"

jobs:
  reminder-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check scheduler
        run: |
          echo "================================="
          echo "SUPER 6 REMINDER SCHEDULER"
          echo "================================="
          echo "Scheduler is working."
          echo "Current UTC time:"
          date -u
          echo "================================="
